### PR TITLE
Performance improvements and rename taps to accumulators

### PR DESCRIPTION
**Pull request by zsoerenm**
Improved performance of correlators and renamed `taps` to `correlators` for clarification

### CODE REVIEW

**Comment by dominformant** [comment]
I understand the idea of renaming the `taps` to `correlators`, as `taps` probably is not the right name here. But I'm afraid, `correlators` could be ambiguous, if we have a `correlator` object, which consists of `correlators` of a different type, which was the idea in not calling it `correlators` when implementing the `GenericCorrelator` type. However, I don't have a better idea on how to call it.

**Comment by zsoerenm** [comment]
Good point, but still I would leave it like that. I think, if we are specific about this in the documentation, e.g. one is the correlator type (a name) and the other is the actual correlator, this will work out.
Oh, another name could be `accumulator`.

**Comment by dominformant** [comment]
I agree, `accumulator` would be a good name.

**Comment by zsoerenm** [comment]
Alright, I made a few more changes here:
- Renamed `taps` to `accumulators`
- Replaced `GenericCorrelator` with `EarlyPromptLateCorrelator`

The `GenericCorrelator` was an `EarlyPromptLateCorrelator` with more than 3 accumulators. I removed the early, prompt and late index from the correlator, since that wasn't variable enough.
The index can now be chosen with a parameter that is passed to the `track` function. For early and late it looks for the index that results to a code phase shift of roughly 0.5 by default. The prompt is now always the accumulator, which has a zero sample shift.

This removes a lot of the code duplication, that we had before between `GenericCorrelator` and `EarlyPromptLateCorrelator`.
By the way it is now really easy to add a  `VeryEarlyPromptLateCorrelator` by just defining the type and make it a subtype of AbstractCorrelator. The `EarlyPromptLateCorrelator` restricted to have at least 3 accumulators.

**Review by dominformant — APPROVED** [review]

**Pull request merged**
