### PR TITLE
Allow image band processing

### PR DESCRIPTION
**Pull request by dominformant**
Added a parameter to `TrackingState` in order to process signals recorded in image bands resulting in a sign change between carrier and code doppler.

### CODE REVIEW

**Comment by zsoerenm** [comment]
Isn't the image band only a problem of real valued signals?

**Comment by dominformant** [comment]
Currently, this pull request only changes the initialization of the code doppler and the carrier aiding, however, I would suggest to also negate the output of the carrier doppler if an image band is processed, as this value should reflect the doppler frequency of the received signal and not the doppler of the digitized signal. Alternatively, we could add an access method `get_true_carrier_doppler`(or something...). What is your opinion on that @zsoerenm?

**Comment by zsoerenm** [comment]
okay, I see. So I guess you'll need to filter out one side of the band to reconstruct the baseband signal. Why do you filter the mirrored signal and not the un-mirrored signal?

**Comment by dominformant** [comment]
I dont' really get what you mean. If bandpass undersampling is used to record a signal with a sampling rate below the intermediate frequency of the analog frontend, the spectrum of the recorded signal is mirrored and there is (in my opinion) no way to reconstruct the original signal. However, this mirrored signal can be processed just as the "original" one, the only difference is that the sign of the carrier doppler changes (but not the sign of the code doppler).

**Comment by zsoerenm** [comment]
Even for subsampling you'll get copies of mirrored and unmirrored signals. You'll have to filter the correct signal, don't you?
grafik

Refer to page pp. 52 (62) in the above presentation

**Comment by dominformant** [comment]
Okay, now I understand. However, this assumes, that no additional processing of the signal has happened after the sampling. If however, a (complex sampling) SDR is used for recording, this will eliminate the "mirror" signal, which in case of an inverting frontend actually is the correct signal.

**Comment by zsoerenm** [comment]
Okay, I see. I think you can mirror the mirrored signal back to its original form, if you take the complex conjugate of the signal (see pp. 7 (62)). Does this work for you? 
I'm unsure if we should handle this niche case in Tracking.jl

**Comment by dominformant** [comment]
I also thought about that and it actually works for the classical signals, however I'm not sure if the resulting conjugate spectrum might lead to problems with some of the modern signals. Nevertheless, I'm going to close this for now, as adapting the signal even solves the "problem" with negated carrier dopplers.

**Pull request closed without merging**
