### PR TITLE
Use code generation from `GNSSSignals.jl`

### PR DESCRIPTION
**Pull request by dominformant**
The tracking of BOC-Signals requires to load the code with non-integer phases to enable the subcarrier generation.
Using `FixedPointNumbers.jl` gives comparable speed as the current implementation while providing the fractional phase in the code access.

### CODE REVIEW

**Comment by zsoerenm** [comment]
I have added CI for all new pull request right here on Github. There are still some errors (see above).

**Comment by dominformant** [comment]
Actually, the code generation can simplified here, as soon as JuliaGNSS/GNSSSignals.jl#21 is merged.

**Comment by zsoerenm** [comment]
The test is failing because the minimal Julia version that is required by the new GNSSSignals.jl is v1.6
So I guess Project.toml and `.github/workflows/ci.yml` need to reflect this change

**Comment by dominformant** [comment]
Code generation is now implemented by `GNSSSignals.jl` to enhance code reuse. Minimum Julia version is increased to 1.6 as required by `GNSSSignals.jl`.

**Review by zsoerenm — APPROVED** [review]

**Pull request merged**
